import { StyleSheet, StatusBar } from "react-native";
export const styles = StyleSheet.create({
  container: {
    flex: 1,
    marginTop: 0,
    alignItems: "center",
    backgroundColor: "#E2EAF4",
  },
  createButtonContainer: {
    padding: 15,
    alignSelf: "flex-start",
  },
  hundredpercenContainer: {
    flex: 0.8,
    width: "100%",
  },
  eightypercenContainer: {
    flex: 1,
    width: "80%",
  },
  createGroupContainer: {
    flex: 1,
    width: "80%",
    marginTop: 20,
  },
  timerContainer: {
    backgroundColor: "#F78473",
    padding: 12,
    borderWidth: 2,
  },
  createButton: {
    backgroundColor: "#F78473",
    width: "50%",
    paddingVertical: 10,
    paddingHorizontal: 20,
    borderRadius: 30,
    shadowOffset: { width: 5, height: 4 },
    shadowColor: "#000",
    shadowOpacity: 0.4,
    elevation: 5,
  },
  item: {
    flexDirection: "row",
    width: "95%",
    backgroundColor: "#FAFAFA",
    padding: 15,
    borderRadius: 20,
    borderColor: "#000",
    shadowOffset: { width: 5, height: 4 },
    shadowColor: "#000",
    shadowOpacity: 0.4,
    elevation: 5,
    marginHorizontal: 8,
    marginVertical: 8,
  },
  smallDot: {
    padding: 5,
    backgroundColor: "red",
    borderRadius: 4,
    marginRight: 10,
  },
  groupName: {
    flex: 1,
    fontSize: 22,
  },
  groupTitle: {
    fontSize: 18,
    fontWeight: "bold",
  },
  groupTextInput: {
    padding: 10,
    paddingHorizontal: 25,
    borderRadius: 50,
    borderColor: "#000",
    backgroundColor: "#fafafa",
    shadowOffset: { width: 5, height: 4 },
    shadowColor: "#000",
    shadowOpacity: 0.4,
    marginVertical: 5,
    elevation: 5,
    fontSize: 20,
    fontWeight: "bold",
  },
  unsubmittedButton: {
    padding: 15,
    borderRadius: 50,
    borderColor: "#000",
    backgroundColor: "#313B68",
    shadowOffset: { width: 5, height: 4 },
    shadowColor: "#000",
    shadowOpacity: 0.4,
    opacity: 0.6,
    marginTop: "10%",
    elevation: 5,
  },
  friendsNotjoined: {
    width: "95%",
    flexDirection: "row",
    padding: 10,
    borderRadius: 50,
    borderColor: "#000",
    backgroundColor: "#767676",
    shadowOffset: { width: 5, height: 4 },
    shadowColor: "#000",
    shadowOpacity: 0.4,
    marginVertical: 5,
    elevation: 5,
  },
  friendsName: {
    fontSize: 20,
    flex: 1,
    marginLeft: 10,
  },
});
